server:
  port: 8080
#设置mysql参数
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: zhang2000
    driver-class-name: com.mysql.cj.jdbc.Driver